name: 'Setup env'
description: 'Sets the default environment variables'
inputs:
  environment-name:
    description: 'The name of the environment'
    required: true
    default: 'Preview'
  vercel-token:
    description: 'The Vercel token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      id: install-vercel
      run: npm install --global vercel@latest
      shell: bash
    - name: Pull Environment variables from Vercel
      run: |
        vercel pull --yes --environment=${{ inputs.environment-name }} --token=${{ inputs.vercel-token }}
      shell: bash
    - name: Set ENV variables from .env.preview.local
      run: |
        cat .vercel/.env.${{ inputs.environment-name }}.local
        cat .vercel/.env.${{ inputs.environment-name }}.local >> $GITHUB_ENV
      shell: bash
    - name: Set build environment variables
      id: set-build-number
      run: |
        echo DB $DATABASE_URL
        echo "PUBLIC_BUILD=${{ github.ref_name }} - ${{ github.run_number }}" >> $GITHUB_ENV
        echo "PUBLIC_AUTH0_CLIENT_ID=GLHJJUCeLrnWqcYZ0tf9uTpmIwXjmLjP" >> $GITHUB_ENV
        echo "PUBLIC_AUTH0_DOMAIN=dejanvasic.au.auth0.com" >> $GITHUB_ENV
        echo "PUBLIC_AUTH0_AUDIENCE=https://api-notes.dejanvasic.me" >> $GITHUB_ENV
      shell: bash
