name: 'Setup env'
description: 'Sets the default environment variables'
inputs: 
  database-url:
    description: 'Database URL'
    required: true
  prisma-field-encryption-key:
    description: 'Prisma field encryption key'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo "PUBLIC_BUILD=${{ github.ref_name }} - ${{ github.run_number }}" >> $GITHUB_ENV
        echo "PUBLIC_AUTH0_CLIENT_ID=GLHJJUCeLrnWqcYZ0tf9uTpmIwXjmLjP" >> $GITHUB_ENV
        echo "PUBLIC_APUBLIC_AUTH0_DOMAIN=dejanvasic.au.auth0.com" >> $GITHUB_ENV
        echo "PUBLIC_AUTH0_AUDIENCE=https://api-notes.dejanvasic.me" >> $GITHUB_ENV
        echo "PRISMA_FIELD_ENCRYPTION_KEY=${{ inputs.PRISMA_FIELD_ENCRYPTION_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ inputs.DATABASE_URL_STAGING }}" >> $GITHUB_ENV
      shell: bash
