name: Deploy prod
env:
  AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
  AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PUBLIC_BUILD: ${{ github.ref_name }}-${{ github.run_number }}
  PRISMA_FIELD_ENCRYPTION_KEY: ${{ secrets.PRISMA_FIELD_ENCRYPTION_KEY }}
  PRODUCTION_DOMAIN: notes.vasic.com.au
  PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  SES_AWS_ACCESS_KEY_ID: ${{ secrets.SES_AWS_ACCESS_KEY_ID }}
  SES_AWS_SECRET_ACCESS_KEY: ${{ secrets.SES_AWS_SECRET_ACCESS_KEY }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy_production:
    name: Production deploy
    concurrency: production_deploy
    environment:
      name: production
      url: https://${{ env.PRODUCTION_DOMAIN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Deploy
        run: |
          npm install --global vercel@canary
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
